Example/SDWebImageWebPCoderExample.xcodeproj/project.pbxproj, SDWebImageWebPCoder.xcodeproj/project.pbxproj, SDWebImageWebPCoder.xcodeproj/project.xcworkspace/contents.xcworkspacedata, SDWebImageWebPCoder/Classes/SDImageWebPCoder.h, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, SDWebImageWebPCoder/Classes/UIImage+WebP.h, SDWebImageWebPCoder/Classes/UIImage+WebP.m
This merge request fixes / reffers to the following issues: ...
In previous version of SDWebImage, we define a macro `SD_WEBP` to indicate that we supports WebP image and link libwebp third party dependency. Using the macro can avoid actually generate the unused class symbols and files for user who don't need webp (Which may increase the framework binary size).
However, now, we move the `SDImageWebPCoder` into this dedicated repo. So this means, people who add dependency to our new repo indeed want WebP supports. Thoes `SD_WEBP` macro define does not do anything.
It's not time to remove them, to avoid unused extra process for some user (For example, in the previous version, if you need to build a embedded framework link the `SDWebImage/WebP`, you also to inherit this `SD_WEBP` macro in …
=> Remove the extra SD_WEBP macro define. Since now we move to a dedicated repo

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See: https://github.com/SDWebImage/SDWebImage/pull/2585
This is bugfix for 5.0 version WebP coder as well. Besides the code from master branch of SDWebImage.
Since now WebP coder support Animation protoocl. And Animation decoding need to query `animatedImageFrameAtIndex:` really frequently, that ICC Profile colorSpace should be kept associated to coder instance, like what we've done for `_canvas` property.
=> Fix that WebP image with ICC Profile does not show color correctly, should use the profile colorspace instead of device colorspace

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
This fix the potential leak of `WebPChunkIterator`. The libwebp says: 
> // Call WebPDemuxReleaseChunkIterator() when use of the iterator is complete.
This also imporve the performance by checking the ICC flags before actual grab the chunk.
=> Fix the potential leak of chunk iterator used for ICC Profile colorSpace check

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
The `vImageConvert`, should be release after the usage. However, current code does not and cause a small leakage.
See documentation here of `vImageConverter_CreateWithCGImageFormat`:
```
*  @return  A vImageConverter object with reference count of 1 is created. If the call fails due to an error, then NULL
*  will be returned. Use vImageConverter_Release to release your reference to it and allow the resources used
*  by the converter to be returned to the system.
```
=> Fix one leak of vImageConvertor

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
Add a backup check of image.images.
See the demo code to trigger this issue:
```objectivec
UIImage *animatedImage = [UIImage sd_imageWithGIFData:gifData];
NSData *staticWebP = [SDImageWebPCoder.sharedCoder encodedDataWithImage:animatedImage format:SDImageFormatWebP options:@{SDImageCoderEncodeFirstFrameOnly : @(YES)}]
NSParamAsset(staticWebP);
```
=> Fix the issue when provide a `UIAnimatedImage` and encode it into a static WebP failed

Example/SDWebImageWebPCoderExample/ViewController.m, SDWebImageWebPCoder.podspec, SDWebImageWebPCoder.xcodeproj/project.pbxproj, SDWebImageWebPCoder/Module/SDWebImageWebPCoder.modulemap
Fix that current SDWebImageWebP, does not including the standard umbrella header (Which should be `SDWebImageWebPCoder.h`). Seems that during migration the umbrella header is missed.
=> Fix the umbrella headers and modulemap for CocoaPods

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
Review and See: https://github.com/SDWebImage/SDWebImage/pull/2621
=> Fix that WebP with custom ICC Profile will randomly crash, because `CGColorSpaceCreateWithICCProfile` does not copy the ICC data pointer

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See: https://github.com/SDWebImage/SDWebImage/pull/2627
=> Fix the issue when WebP contains the ICC Profile with colorSpace other than RGB, which cause the CGImageCreate failed

SDWebImageWebPCoder/Classes/SDImageWebPCoder.h, SDWebImageWebPCoder/Classes/UIImage+WebP.h
Hi, I added `@import UIKit;` at `UIImage+WebP.h` to fix the issue that I mentioned at this PR's title.
The issue can be reproduced using a `Podfile` with `use_modular_headers!`, to link this library as a static library, as follows:
```
/<Your Project>/Pods/Headers/Public/SDWebImageWebPCoder/UIImage+WebP.h:12:12: Declaration of 'UIImage' must be imported from module 'UIKit.UIDocumentBrowserAction' before it is required
```
and
```
/<Your Project>/Pods/Headers/Public/SDWebImageWebPCoder/UIImage+WebP.h:12:12: Definition of 'UIImage' must be imported from module 'UIKit.UIImage' before it is required
```
=> Fix the issue that could not compile SDWebImageWebPCoder when using CocoaPods with use_modular_header!

SDWebImageWebPCoder.xcodeproj/project.pbxproj
The generated project seems using `SDWebImageWebPCoder_macos.framework`, which is not great. Instead, using `SDWebImageWebPCoder.framework`.
Seems a Xcode bug, because the build settings already setup to use the `MODULE_NAME`. But it's cached into the `pbxproj` file and not get updated.
=> Update to fix the wrong product name `SDWebImageWebPCoder_macos.framework` for macOS on Carthage users

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See Bug demo: https://github.com/krze/SDWebImage-WebP-Bug
Issue: https://github.com/SDWebImage/SDWebImage/issues/2835
I found the logic bug. The code comment does not match what it do.
```
// Draw from range: [startIndex, endIndex)
while ((size_t)iter.frame_num < endIndex && WebPDemuxNextFrame(&iter));
```
Before we call `WebPDemuxNextFrame`, the `iter.frame_num` is the 0-based previous frame index + 1. So the endIndex should not use `+1` as well.
For example:
request index == 1
frame.fromIndex == 0
frame.endIndex == 1
it should only call `sd_blendWebpImageWithCanvas` once, then call `sd_drawnWebpImageWithCanvas` once. But however, current code cause that call `sd_blendWebpImageWithCanvas` twice. This is the problem.
Change the end condition of that while loop, should just check `< …
=> Fix the Animated WebP coder the frame blend index calculation issue, he end condition should be only `endIndex` to match the behavior.

Example/SDWebImageWebPCoderExample.xcodeproj/project.pbxproj, SDWebImageWebPCoder.xcodeproj/project.pbxproj, SDWebImageWebPCoder.xcworkspace/contents.xcworkspacedata, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
This API is deprecated from iOS 11+. The function is the same, just naming (What CoreGraphics team do ???)
=> Fix the warning of deprecated API `CGColorSpaceCreateWithICCProfile`

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, SDWebImageWebPCoderTests/SDWebImageWebPCoderTests.m
This is a quick fix for #29.
For Static WebP, we don't create extra CGContext to consume RAM. Instead, just do the static WebP decoding.
Note this method still need to be protected in the LOCK/UNLOCK code, because multiple thread can access the `animatedImageFrameAtIndex:`, and we share the global `_demux` instance.
The root solution is in 5.4.2 of SDWebImage, see: https://github.com/SDWebImage/SDWebImage/pull/2924
=> Fix the issue when WebP is static webp, the `SDAnimatedImageCoder` protocol implementation still create CGContext, this can reduce RAM usage

Cartfile, Cartfile.resolved, Example/SDWebImageWebPCoderExample/ViewController.m, SDWebImageWebPCoder.podspec, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, SDWebImageWebPCoderTests/Podfile, SDWebImageWebPCoderTests/SDWebImageWebPCoderTests.m
See thumbnail decoding PR: https://github.com/SDWebImage/SDWebImage/pull/2922
=> WebPCoder now supports the thumbnail decoding

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
The libwebp progressive API does not have something like `use_scaling`. Sadly :(
So, fallback to use the `CGImageCreatedScaled`
=> Fix the issue that thumbnail decoding does not works for progressive webp image

Example/SDWebImageWebPCoderExample/ViewController.m, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See the demo video:
[Progressive Animated WebP.mov.zip](https://github.com/SDWebImage/SDWebImageWebPCoder/files/4080406/Progressive.Animated.WebP.mov.zip)
Sample WebP Image (1.2MB): https://static.ezgif.com/images/format-demo/butterfly.webp
Note:
For UIImageView using the `SDWebImageProgressiveLoad`, the decoder will only decode animation first frame image, this keep the exist behavior for GIF/APNG.
=> Feature - Supports Progressive Animated WebP (Important)

Cartfile, Cartfile.resolved, Package.swift, SDWebImageWebPCoder.podspec, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See 5.7.0 feature: [maxFileSize](https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.0)
libwebp Encoding API: https://developers.google.com/speed/webp/docs/api#advanced_encoding_api
=> Upgrade the dependency to SDWebImage 5.7, supports the maxFileSize encoding options, as well as enabling the thread-encoding for speedup

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, Tests/SDWebImageWebPCoderTests.m
This is what SDWebImage 5.7 introduced, see: https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.2
=> Feature WebP Encoding max pixel size (Thumbnail Encoding)

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See more: https://github.com/SDWebImage/SDWebImage/pull/3128
=> Replace the dispatch semaphore into os_unfair_lock, copied from SDWebImage Core

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, Tests/SDWebImageWebPCoderTests.m
Found out that zero cannot be given as parameter to WebP options. For example, code:
```
let options = [.encodeWebPMethod: 0, .encodeWebPAlphaCompression: 100]
let data = SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: options)
```
Does not work correctly. Default value for WebP method (4) is used instead of 0.
Issue is caused by the fact that comparison 
```
if ([options[SDImageCoderEncodeWebPMethod] intValue])
```
results to false when intValue is 0.
Fixed by changing the logic of how it is concluded whether value for certain option has been provided. Also updated unit tests so they catch similar issues in future.
=> Fixed bug that caused WebP parameter value 0 to be ignored

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
See Apple's documentation about `vImageBuffer_InitWithCGImage`
> You're responsible for releasing the memory that buf->data points to back to the system using free().
https://developer.apple.com/documentation/accelerate/1399118-vimagebuffer_initwithcgimage?language=objc
=> Fix the encoding leak when input CGImage is not RGBA8888 or RGB888

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
This quickly fix the #64, without bumping the SDWebImage Core dependency version
=> Fix the encoding maxPixelSize logic (patch)

Cartfile, Package.swift, Podfile, SDWebImageWebPCoder.podspec, SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
This using the new calculation from SDWebImage Core, which bump the minor version (0.9.0+)
This depends on https://github.com/SDWebImage/SDWebImage/pull/3359
=> Fix the encoding maxPixelSize logic using 5.13.0 API

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
=> Fix the thread safe issue for accessing array with index, which may happend during incremental decoding

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
1. Use CoreGraphics to avoid extra vImage convert and allocate of decoded thumbnail image buffer
2. Use kvImageNoAllocate to avoi extra vImage to allocate 1x memory buffer (x means the input source image buffer)
See more in : https://github.com/SDWebImage/SDWebImage/issues/3508
=> Reduce memory usage peak when using thumbnail animated WebP decoding and encoding

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, SDWebImageWebPCoder/Classes/SDWebImageWebPCoderDefine.h, SDWebImageWebPCoder/Classes/SDWebImageWebPCoderDefine.m, Tests/SDWebImageWebPCoderTests.m
This PR adds a `SDImageCoderEncodeWebPLossless` option to enable lossless mode on webp encoder.
=> Enable lossless mode

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
Also, fallback when the libwebp don't support the target bitmap info, should not just return nil
This close #86
=> Support to detect the RGB16 bitmap info, fix the iOS 11- decode issues

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m, Tests/SDWebImageWebPCoderTests.m
Just translate into RGBA first, don't need extra code to re-implements monochrome WebP encoding
This close #94
=> Fix the issue when monochome colorspace cause the WebP encoding failed

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
Using transform currently
This close #91
=> Fix the issue when EXIF orientation does not keep during the libwebp encoding

SDWebImageWebPCoder.podspec
The old libwebp CocoaPods (maybe 1.0) contains issues for public headers
This close #106
=> Fix the podspec issue for compatible header search path

SDWebImageWebPCoder/Classes/SDImageWebPCoder.m
NSUInteger limitBytes = 0;
NSNumber *limitBytesValue = options[SDImageCoderDecodeScaleDownLimitBytes];
if (limitBytesValue != nil) {
limitBytes = limitBytesValue.unsignedIntegerValue;
}
_limitBytes = limitBytes; ❌❌❌ **ERROR: limitBytes = 62914560, but _limitBytes = 1。**❌❌❌
// Scale down to limit bytes if need
if (_limitBytes > 0) {
// Hack 32 BitsPerPixel
CGSize imageSize = CGSizeMake(_canvasWidth, _canvasHeight);
CGSize framePixelSize = SDCalculateScaleDownPixelSize(_limitBytes, imageSize, _frameCount, 4);
// Override thumbnail size
_thumbnailSize = framePixelSize;
_preserveAspectRatio = YES;
}
=> FIX: _limitBytes type error
